version: "3"

services:
  firebird-rest-relay:
    image: alpine/socat
    restart: unless-stopped
    depends_on:
      - nginx-proxy
    command: "TCP-LISTEN:5555,fork,reuseaddr TCP:host.docker.internal:4444"
    container_name: firebird-rest-relay
    expose:
      - 5555
    environment:
      VIRTUAL_HOST: firebird.finexa.no
      LETSENCRYPT_HOST: firebird.finexa.no
      LETSENCRYPT_EMAIL: "it-support@finexa.no"
    networks:
      service_network:

  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    extra_hosts:
      - localhost:192.168.65.10
    container_name: nginx-proxy
    networks:
      service_network:
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html


  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: unless-stopped
    environment:
      NGINX_PROXY_CONTAINER: "nginx-proxy"
    networks:
      service_network:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-certs:/etc/nginx/certs
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html

networks:
  service_network:

volumes:
  nginx-certs:
  nginx-vhost:
  nginx-html: